version: '1.0.{build}'

before_build:
  - nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration:
  - Debug
  - Release

build:
  project: Telepathy.sln
  verbosity: minimal

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '**\*.nupkg'

  - path: Telepathy\bin\$(configuration)\
    name: Telepathy
    
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

image: Visual Studio 2017

test_script:
  - '%USERPROFILE%\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:Telepathy.Tests\bin\%CONFIGURATION%\net35\Telepathy.Tests.dll -output:"coverage.xml" -filter:"+[Telepathy*]* -[Telepathy.Tests*]* "'

install:
  - cinst docfx

environment:
  github_email:
    secure: 5f2P5xlb1MIulsEro35xNsZas33NI4e+xRCkfV/MmCw=
  github_access_token:
    secure: j4LIFPAEoZYOA8J4e3q/Tt0ABHIKBl+vUK7wwS/PmtJR1nYdHMa8cLy6o3EYUoOB

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 

deploy:
  - provider: Environment
    name: nuget-telepathy
    on:
      branch: master

deploy_script:
  - git config --global credential.helper "store"
  - echo "https://$($env:github_access_token):x-oauth-basic@github.com" > "~\.git-credentials"
  - git config --global user.email %github_email%
  - git config --global user.name "Paul Pacheco"
  - git config --list --show-origin
  - ps: ./releaseDocs.ps1
